### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by ToxicBakery** [cforlando/PetAdoption-Android#22]
We need an app icon. @Erin-Denton mentioned iOS may already have one

**Comment by Erin-Denton** [comment]
Do you want the ios ones or do you want me to make an andoid version?

**Comment by JohnLeeroy** [comment]
512x512 icon and use [asset studio](http://romannurik.github.io/AndroidAssetStudio/icons-launcher.html#foreground.space.trim=1&foreground.space.pad=0&foreColor=607d8b%2C0&crop=0&backgroundShape=square&backColor=ffffff%2C100&effects=none) to generate several sized icons.
