### ISSUE TITLE
Find new image for toolbar of ListActivity

### ISSUE THREAD

**Issue by JohnLeeroy** [cforlando/PetAdoption-Android#36]
It is currently empty and should be the attached photo.  Image will be posted in a comment in the near future.

The image should be related to the Town of Lady Lake or animal adoption.

**Comment by JohnLeeroy** [comment]
The blank purple area on the top of the screen is where the image would be found.

![device-2017-02-20-194935](https://cloud.githubusercontent.com/assets/2716866/23146558/dca64908-f7a5-11e6-8bd5-71bd917d91c4.png)

**Comment by LondonAtlas** [comment]
Not needed
