### ISSUE TITLE
Tapping on Email from Details Fragment causes app to crash

### ISSUE THREAD

**Issue by WERUreo** [cforlando/PetAdoption-Android#41]
Since I only have access to the Android emulator to test this, this may be a non-issue.  When on the Details Fragment for a pet, I tapped the Email button (?) and the app crashed.

**Comment by ToxicBakery** [comment]
Still shouldn't crash but likely you do not have a mail client that handles mail intents.

**Comment by ToxicBakery** [comment]
Same issue clicking the phone on a tablet.
