### ISSUE TITLE
Parse Petfinder Descriptions for information

### ISSUE THREAD

**Issue by JohnLeeroy** [cforlando/PetAdoption-Android#75]
Descriptions from the PetFinder api may contain phone numbers or emails that we need to capture and use.  Making them clickable in the description is also desired.

**Comment by JohnLeeroy** [comment]
After some discussion, we would like refine the parsing algorithm and make sure it's relatively accurate.  This issue has new requirements of making sure any web links, emails, or phone numbers are clickable in the description and open up the appropriate app (phone number opens the dialing app, etc)

**Comment by ToxicBakery** [comment]
You can do that with Linkify
https://developer.android.com/reference/android/text/util/Linkify.html
